### ISSUE TITLE
Eldritch Guardian?

### ISSUE THREAD

**Issue by DanZinagri** [YLMstring/PrestigePlus#10]
I guess i'm not sure if this is a bug, or a question on intent.

So the tabletop version you're meant to use a familiar; which with that let you increase the size of the familiar it basically became a stand-in (and with some of the improved familiars potentially better) animal companion. Here you get the familiar, but as they're just passive buffs in the game and not interactable this doesn't work.

So i see that it shares the feats with animal companions you have; which my question becomes; is this meant to give you an animal companion or is this an archetype that only works with gestalt characters? Because it seems very odd to have an archetype to share feats with an animal companion on on class that does not gain one.

**Comment by YLMstring** [comment]
It only works with multiclassing characters, or you can take animal companion feat chain (TTT)

**Comment by DanZinagri** [comment]
Ok; that seems odd to me that its primary feature doesn't work by itself; i guess i could just use toybox to cheat in those feats, or just gestalt to make it functional.

**Comment by YLMstring** [comment]
It's mainly because fighter has a decent power level already, giving him an animal companion is probably too much, but everyone has their own play style :)
