### ISSUE TITLE
2.5 appears to break gestalt options

### ISSUE THREAD

**Issue by anoldwotrplayer** [YLMstring/PrestigePlus#14]
Really like your work and enjoying prestige plus.  When I updated PP to 2.5.0  and gestalt character's level suddenly shot up to the combined total of all class levels.

Additionally if I attempted to make a gestalt character all the I could tick all the boxes as normal but it combined all the levels on completion.

Rolling back to 2.4.4 and all the gestalt classes worked again.

Again thanks for your fantastic work.

**Comment by YLMstring** [comment]
2.5.1 should fix it, now the mod no longer recalculate character level if you don't have aligned class
In other words, don't take aligned class when using toybox gestalt 0v0
