### ISSUE TITLE
Duplicate Features from other mod

### ISSUE THREAD

**Issue by nextentlligods** [YLMstring/PrestigePlus#15]
It seems that the Catechesis feature of Hell Knight Signifer has been already implemented in MorvarchsPlaystyleExpansions, could you make it compatible?

**Comment by YLMstring** [comment]
Aw people lured me in to making duplicate features again

**Comment by YLMstring** [comment]
I can't find their Catechesis in game or in code?
It probably didn't work and they removed it

**Comment by nextentlligods** [comment]
It seems that the author didn't push the commit in time, perhaps you could download the source code in the release page?

**Comment by YLMstring** [comment]
It turns out mine is the better one, because his stuff clearly doesn't support ec domains
If you play with his mod, don't select pp Catechesis when leveling up then you'll be fine
