### ISSUE TITLE
Medusa strike

### ISSUE THREAD

**Issue by astrocastro** [YLMstring/PrestigePlus#2]
Wow, the grapple mechanic is really impressive! Do you think that you would be able to add medusa strike as a monk bonus feat?

**Comment by YLMstring** [comment]
You mean Medusa's Wrath?

**Comment by YLMstring** [comment]
I just realized - Feats from style feat chains can work without the style itself? So you can take feats from different styles and they work together?

**Comment by astrocastro** [comment]
Ah, you are right, I meant medusa's wrath.  In TT, it's offered as a bonus feat (not requiring the previous feats in the chain) t level 10 and doesnt require the previous feats in the chain to activate RAW.  I can't think of others off the top of my head but I assume if the feat RAW doesn't mention needing the other feats to activate then it should be fine.  However, you would still need the other feats to choose it as an option if not offered as a bonus feat.  You can compare pummeling bully to medusa's wrath to see the difference in the text: https://www.d20pfsrd.com/feats/combat-feats/pummeling-bully-combat/ vs https://www.d20pfsrd.com/feats/combat-feats/medusa-s-wrath-combat/

**Comment by YLMstring** [comment]
Looks pretty cool! I won't be adding the first two feats though, maybe merging it with another style while being a monk bonus feat lol
