### ISSUE TITLE
Unable to see Heritor Knight in Class List

### ISSUE THREAD

**Issue by Envibel** [YLMstring/PrestigePlus#22]
I'm the same Envibel that asked about this in the discord. Thank you for putting out a new version, I hadn't had a chance to check it out until now. Unfortunately, I still can't see Heritor Knight in the class list though. Fwiw I do have it enabled in the mod menu settings.

**Comment by YLMstring** [comment]
umm, can't replicate here, do you have:
[23.3727 - Mods]: BlueprintCore.BlueprintConfigurator: HeritorKnight (BlueprintCharacterClass) failed validation
in your gamelogfull?

**Comment by Envibel** [comment]
I have no mention of HeritorKnight in my gamelogfull

**Comment by Envibel** [comment]
Small addendum, I have tried manually removing the Prestige Plus folder from my mods folder and doing a fresh install. Even then I do not see the class in the list

**Comment by YLMstring** [comment]
mod list? since my friend and I can see it lol

**Comment by Envibel** [comment]
Sure, happy to provide:

AutoMount
Bubble Buffs
Bubble Tweaks
Combat Relief (Updated)
DarkCodex
DataViewer
Expanded Content
Expanded Epilogue
Homebrew Archetypes
Martial Excellence
Mewsifier Console
Mod Menu
Multiple Archetypes
No Fil Grain
No TeleportationCircle Restrictions
Phoenix's Cantrips
Prestige Plus
Puzzle Skip
Random Equipment
Respec Mod
Spars Sorcerous Sundries
TTT Base
TTT Core
TTT Mythic Rework
Tome of the Firebird
Toybox
Turnbased Combat Delay
Visual Adjustments 2
Weapon Focus Plus

**Comment by YLMstring** [comment]
fixed (hopefully) in 2.8.2?

**Comment by Envibel** [comment]
It's fixed, I can now see it with 2.8.2! Thank you!
