### ISSUE TITLE
zhCN localization is not complete

### ISSUE THREAD

**Issue by nixgnot** [YLMstring/PrestigePlus#3]
hi here. i like your mod but i found that zhCN localization is not complete.

may i help or there are other guys do it but just work-in-progress?

**Comment by YLMstring** [comment]
没翻的部分都是我懒癌发作的结果
帮我翻翻好不好QwQ

**Comment by nixgnot** [comment]
> 没翻的部分都是我懒癌发作的结果 帮我翻翻好不好QwQ

笑死 2333
不过我现在都是拿QuickLocalization mod做外置汉化文件的，省得每次都还要找作者合并 :P

**Comment by YLMstring** [comment]
奥妙重重.jpg
