### ISSUE TITLE
Lore Warden and Warlord cannot be chosen

### ISSUE THREAD

**Issue by nextentlligods** [YLMstring/PrestigePlus#6]
I use 'multiple archetype' mod simutaneously, and that may cause fighter archetypes Lore Warden and Warlord not able to be selected which are gray, can't be clicked.
Eldritch Guaedian should lose his bravery at lv 18, incidentally.

**Comment by YLMstring** [comment]
Multiple archetype works fine for me, hmm.
I'll remove that extra bravery next patch!

**Comment by YLMstring** [comment]
It breaks somehow when using a certain mod. Since my code looks fine? it's probabaly has something to do with their content.
We are unable to narrow down which mod it is at the moment, so if anyone else encounter this issue, post your mod list here and we can cross check

**Comment by YLMstring** [comment]
I trigger it when testing something else lol
Investigating...

**Comment by nextentlligods** [comment]
The problem mods are EnduringRework and MicroscopicContentExpansion.

**Comment by YLMstring** [comment]
I have no problem running with those while I trigger the bug when I make myself load after TTT-base
So I did something about it...
Hopefully v1.5.0 won't have this issue!

**Comment by nextentlligods** [comment]
Problem solved. Thanks for the fix!
