### ISSUE TITLE
Save game doesn't load after updating from v1.4.0 to v1.5.0 or v1.6.0

### ISSUE THREAD

**Issue by DanScallion** [YLMstring/PrestigePlus#8]
After updating to v1.5.0 or v1.6.0 from v1.4.0 save game loads to 59% then quits to menu. Reverting to v1.4.0 allows me to play normally. 
Logs: https://drive.google.com/file/d/1cdd4W6BMqKjnc0zrxW6NxcPlm4F4V7oP/view?usp=sharing

**Comment by YLMstring** [comment]
The log says TTT can't load armor training. It's probably due to my changing load order with TTT in 1.5.0
Do you use lore warden or warlord? If so, retraining the character in 1.4.0 into other classes might solve this

**Comment by DanScallion** [comment]
No, I do not use lore warden nor warlord. Regill is a fighter so I retrained him into other class but it still doesn't load. I have no mercs nor other fighter companions. https://drive.google.com/open?id=1--e4RtNO3b0ECL6dUum2W1cpEwovlgKh&usp=drive_fs

**Comment by YLMstring** [comment]
hmm, no idea then
there're 2 exceptions, one belongs to fire bird mod, the other says Failed to load blueprint by guid 0cfa35b0e58244e1926e5673e065392a
but I don't have any feature by that guid either
Try asking in the discord server (with the mew file)? lol other devs might know what happened here

**Comment by YLMstring** [comment]
I suspect changing load orders leads to unpredictable mod compatibility issues (especially old mods) so your mod list is also relevent

**Comment by YLMstring** [comment]
I have an idea. We can look at v1.4.0's logs and compare, the errors that appear in both are not relevent

**Comment by YLMstring** [comment]
v1.6.1 just reversed mod order changes made in v1.5.0, let's see what this does!
